### ISSUE TITLE
Generate PDF report for GRdrawDRC() function

### ISSUE THREAD

**Issue by mariottoelena** [uc-bd2k/GRmetrics#1]
Hi there,

I'm Elena, postdoc researcher in the Experimental Pharmacology unit of Pediatric Oncohematology lab, University of Padova, Italy.

First of all, thank you for sharing the 'GRmetrics' package with the scientific community. It is very helpful for the high-throughput drug screening that I'm working on. However I'm quite new to R so it's difficult for me to change the code to draw the kind of graphs that I'm interested in.

I would like to draw the curves ("GR" or "rel_cell" metrics) relatives to a single variable (in my case sometimes it's easier to look at the effect of a single agent in all cell lines or, alternatively, the effect of all tested agents per cell line) and then export all graphs in a single PDF or TIFF file. I've already tried to use  the "experiments" argument but it requires both 'cell_line' and 'agent' thus making a very very annoying job for me to write all possible combination (i.e. I've screened 320 drugs in 14 different cell lines)!!!

I know it may be a very dumb issue but I've got stuck with it. I've tried to use the loop function but I cannot get rid off the "experiments" constrain.

Please reach me at elena.mariotto@unipd.it

Thanks again for your job & help

Elena

**Comment by mariottoelena** [comment]
Hi there,

any update?

**Comment by NicholasClark** [comment]
Elena, sorry for the delay.

I'm busy with other projects, but I will try to take a look at this soon.

I believe I removed the pdf option at some point because I was getting confusing errors with it that I couldn’t resolve. I’ll try adding it again… maybe with an updated R version or some updated packages it will work again.

-Nick

**Comment by NicholasClark** [comment]
Elena, when I looked at this, I thought you were referring to the GR calculator web application, where there are issues exporting to PDF. Unfortunately, I spent all day trying to debug the web application and haven't even looked at the R package.

At this point, I just do not have the time to keep up with my current job duties and also debug and update this package.

Apologies,
Nick
